apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: hello-world-virtual-server
  namespace: hello-world
  labels:
    f5cr: "true"
spec:
  host: demo.my-f5.com
  #virtualServerAddress: "10.0.2.100"
  virtualServerName: "hello-world-vs"
  ipamLabel: Production
  pools:
  - path: /
    service: hello-world
    servicePort: 80
    monitor:
      type: http
      interval: 10
      timeout: 31
      send: "/"
      recv: ""
